#!/bin/sh

. "./.CameraConfiguration"

JSON=$(
	cat <<DELIMITER
{
	"ConfigurationToken":"vac",
	"AnalyticsModule":[
		{

			"Parameters":"<Parameters><SimpleItem Name=\"Sensitivity\" Value=\"100\"/><ElementItem Name=\"Layout\"><CellLayout Columns=\"32\" Rows=\"18\"/></ElementItem></Parameters>",
			"Parameters0":"<Parameters><SimpleItem Name=\"Sensitivity\" Value=\"90\"/><ElementItem Name=\"Layout\"><CellLayout Columns=\"32\" Rows=\"18\"/></ElementItem></Parameters>",
			"Name":"Test3",
			"Type":"cellmotiondetector"
		},
		{
			"Parameters":"<Parameters><SimpleItem Name=\"Sensitivity\" Value=\"90\"/><ElementItem Name=\"Layout\"><CellLayout Columns=\"32\" Rows=\"18\"/></ElementItem></Parameters>",
			"Name":"Test4",
			"Type":"cellmotiondetector"
		}
	]
}
DELIMITER
)
json_test analytics/CreateAnalyticsModules
