#!/bin/sh

. "./.CameraConfiguration"

JSON=$(
	cat <<DELIMITER
{
	"ConfigurationToken":"vac",
	"AnalyticsModuleName":[
		"Test1",
		"Test2"
	]
}
DELIMITER
)
json_test analytics/DeleteAnalyticsModules
