#!/bin/sh

. "./.CameraConfiguration"

JSON=$(
	cat <<DELIMITER
{
	"Configuration": {
		"Name": "AEC H.264",
		"UseCount": 2,
		"Token": "aec-h264",
		"Encoding": "G711",
		"Bitrate": 64,
		"SampleRate": 8,
		"Multicast": {
		"Address": {
			"Type": "IPv4",
			"IPv4Address": "224.1.1.1"
		},
		"Port": 5000,
		"TTL": 1,
		"AutoStart": false
		},
		"SessionTimeout": "PT0S"
	},
	"ForcePersistence": true
}
DELIMITER
)
json_test media/SetAudioEncoderConfiguration
