#!/bin/sh

. "./.CameraConfiguration"

JSON=$(
	cat <<DELIMITER
{
    "VideoSourceToken": "src",
    "ImagingSettings": {
        "Brightness": 50,
        "ColorSaturation": 50,
        "Contrast": 60,
        "IrCutFilter": "OFF",
        "Sharpness": 0,
        "WhiteBalance": {
            "Mode": "AUTO"
        }
    },
    "ForcePersistence": false
}
DELIMITER
)
json_test imaging/SetImagingSettings
