#!/bin/sh

. "./.CameraConfiguration"

JSON=$(
	cat <<DELIMITER
{
	"Id": "Jacob/Batalon",
	"Images": [
		"http://$IP/download/facedb/Jacob_Batalon/thumbnail.jpg",
		"http://$IP/download/facedb/Jacob_Batalon/image-0000.jpg",
		"http://$IP/download/facedb/Jacob_Batalon/image-0001.jpg",
		"http://$IP/download/facedb/Jacob_Batalon/image-0002.jpg"
	]
}
DELIMITER
)
json_test analytics/DeleteFaceImages
