#!/bin/sh

. "./.CameraConfiguration"

JSON=$(
	cat <<DELIMITER
{
	"Id": "Jacob/Batalon",
	"FirstName": "SomeFirstName - $RANDOM"
}
DELIMITER
)
json_test analytics/ModifyFace


JSON=$(
	cat <<DELIMITER
{
	"Id": "Jacob/Batalon"
}
DELIMITER
)
json_test analytics/GetFace
