#!/bin/sh

. "./.CameraConfiguration"

JSON=$(
	cat <<DELIMITER
{
  "Configuration": {
    "Name": "Metadata configuration",
    "UseCount": 1,
    "Token": "mdc",
    "PTZStatus": {
      "Status": false,
      "Position": false
    },
    "Events": {
      "Filter": {
        "TopicExpression": [
          {
            "Dialect": "http://www.onvif.org/ver10/tev/topicExpression/ConcreteSet",
            "Expression": "FilterTopicExpression1"
          },
          {
            "Dialect": "http://www.onvif.org/ver10/tev/topicExpression/ConcreteSet",
            "Expression": "FilterTopicExpression2"
          }
        ],
        "MessageContent": [
          {
            "Dialect": "http://www.onvif.org/ver10/tev/messageContentFilter/ItemFilter",
            "Expression": "FilterMessageContent1"
          },
          {
            "Dialect": "http://www.onvif.org/ver10/tev/messageContentFilter/ItemFilter",
            "Expression": "FilterMessageContent2"
          }
        ]
      }
    },
    "Analytics": false,
    "Multicast": {
      "Address": {
        "Type": "IPv4",
        "IPv4Address": "224.1.1.1"
      },
      "Port": 5000,
      "TTL": 1,
      "AutoStart": false
    },
    "SessionTimeout": "PT0S",
    "GeoLocation": false,
    "ShapePolygon": false
  },
  "ForcePersistence": false
}
DELIMITER
)
json_test media/SetMetadataConfiguration
